settings:
  name: Google Cloud Storage
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
  rss_page: "whats-new.html"
sidebar:
  entries:
    - title: Google Cloud Storage docs
      url: /index.html
    - title: Release notes
      url: /whats-new.html
    - title: Get started
      entries:
        - title: View your Cloud Storage buckets
          url: /task-viewing-gcp-storage.html
    - title: Manage Cloud Storage buckets
      entries:
        - title: Add Cloud Storage buckets
          url: /task-add-gcp-bucket.html
        - title: Change Cloud Storage bucket settings
          url: /task-change-gcp-bucket-settings.html
        - title: Use NetApp data services with Cloud Storage buckets
          url: /task-gcp-enable-data-services.html
    - title: Knowledge and support
      entries:
        - title: Register for support
          url: /task-support-registration.html
        - title: Get help
          url: /task-get-help.html
    - title: Legal notices
      url: /legal-notices.html
product-family:
  name: BlueXP
  repo: cloud-manager-family
  sidebar_label: All BlueXP documentation
homepage:
  tiles:
    - title: Get started
      links:
        - title: View your Cloud Storage buckets
          url: task-viewing-gcp-storage.html
    - title: Manage Cloud Storage buckets
      links:
        - title: Add Cloud Storage buckets
          url: task-add-gcp-bucket.html
        - title: Change bucket settings
          url: task-change-gcp-bucket-settings.html
        - title: Use NetApp data services with Cloud Storage buckets
          url: task-gcp-enable-data-services.html
    - title: More information
      links:
        - title: Google Cloud Storage documentation for management outside of BlueXP
          url: https://cloud.google.com/storage/docs/creating-buckets
    - title: Blogs & community
      links:
        - title: NetApp Community
          url: https://community.netapp.com/t5/BlueXP-and-Services/ct-p/CDS
        - title: BlueXP blog
          url: https://bluexp.netapp.com/blog/topic/cloud-manager
        - title: Cloud webinars
          url: https://bluexp.netapp.com/events